### ISSUE TITLE
Support package exports in file-extension-in-import

### ISSUE THREAD

**Issue by DMartens** [eslint-community/eslint-plugin-n#50] opened 2022-08-21 12:40 UTC
It seems [package entry points](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#package-entry-points) are not supported by `file-extension-in-import` as it still requires a file extension for them, eg. for `eslint/use-at-your-own-risk`.
But by adding the file extension the file in the package root is required instead.
I am willing to submit a pull request for this.

**Comment by aladdin-add** [comment] 2022-08-22 02:20
I was able to repro, thanks for the report!

**Comment by kidonng** [comment] 2022-09-08 20:33
#21 might be related.

**Comment by scagood** [comment] 2023-10-26 09:18
You're right here, this is a duplicate of #21

**Closed by scagood** 2023-10-26 09:18 UTC
