### ISSUE TITLE
eslint-plugin-n fails on Node 14 

### ISSUE THREAD

**Issue by pacostas** [eslint-community/eslint-plugin-n#121] opened 2023-09-21 13:01 UTC
## Environment
Node version: v14.21.3
npm version: 6.14.18
Local ESLint version: 8.48.0
Local eslint-plugin-n: 16.1.0
Global ESLint version: N/A
Operating System: Fedora 38 , Linux 6.4.14-200.fc38.x86_64 x86_64 GNU/Linux

## Steps to reproduce
* Create any nodejs project
* install eslint-plugin-n
* do `npm run lint`

Throws below error.

```
/path/to/project/kube-service-bindings/node_modules/eslint-plugin-n/lib/util/get-typescript-extension-map.js:43
        backward[javascript] ??= []
                             ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/path/to/project/kube-service-bindings/node_modules/eslint-plugin-n/lib/util/map-typescript-extension.js:5:35)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

```

**Comment by aladdin-add** [comment] 2023-09-22 02:12
Duplicate of #118

**Closed by aladdin-add** 2023-09-22 02:12 UTC
