### ISSUE TITLE
Bug: no-missing-require incorrectly flagging module as missing

### ISSUE THREAD

**Issue by nzakas** [eslint-community/eslint-plugin-n#242] opened 2024-04-11 20:33 UTC
### Environment

Node version: v20.11.0
npm version: v10.4.0
ESLint version: v9.0.0
eslint-plugin-n version: v17.2.0
Operating System: win32 10.0.19045

### What rule do you want to report?

no-missing-require

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint/pull/18313

### What did you expect to happen?

That the rule would correctly find the module `@humanwhocodes/retry`. 

Worked in v16.6.2, stopped working in v17.0.0.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment] 2024-04-11 21:51
After some looking, this is related to: https://github.com/eslint-community/eslint-plugin-n/issues/182

The error is that the exports are the wrong way around:
https://github.com/humanwhocodes/retry/blob/8f8af13/package.json#L10-L13

Therefore this error is getting triggered:
https://github.com/webpack/enhanced-resolve/blob/main/lib/util/entrypoints.js#L475

**Comment by voxpelli** [comment] 2024-04-11 22:56
For context: Sounds like this regression is caused by https://github.com/eslint-community/eslint-plugin-n/pull/139 then

@scagood Want help to look into it?

**Comment by scagood** [comment] 2024-04-12 01:00
Yeah, I would tend to agree. I am thinking about what the best course here is.

We could:
1. Ignore the error (but then not have a path)
2. Pr enhanced resolve to allow the error to be ignored via an option (I don't understand why it throws as opposed to just accepting the default as default)

**Comment by aladdin-add** [comment] 2024-04-12 02:16
seems it's working as expected - as said in the node.js docs:
> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last.

https://nodejs.org/docs/latest/api/packages.html

the next steps:
1. it should report the exact error message in the rule, than just ignoring.
2. fix `@humanwhocodes/retry` to put the `default` to last.

**Comment by scagood** [comment] 2024-04-12 08:28
The think that is in in the back of my head is related to this:
> This condition should always come last.

I interpret this as should always be checked last, not should always appear last in the object's properties

I do know that as of `es2020` property ordering is expected (eg in `for-in`). But before that I don't think there was any guarantee of order :thinking:

**Comment by aladdin-add** [comment] 2024-04-12 08:38
maybe (I'm not a native English speaker). but it's also saying:

> Within the ["exports"](https://nodejs.org/docs/latest/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

generally, it should be a best practice to put it in the last.

**Comment by scagood** [comment] 2024-04-12 08:42
Fair point! notes for next time include to read the source! :sweat_smile:

**Comment by voxpelli** [comment] 2024-04-12 10:24
> Note that the "types" condition should always come first in "exports".

Taken from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-also supports this

**Comment by scagood** [comment] 2024-04-12 10:31
I think we should then close this and proceed with #182 (My first attempt to make that more verbose is here: #231)

**Comment by voxpelli** [comment] 2024-04-12 12:27
Well, if node.js can resolve the module and the issue this plugin finds isn’t within the project that runs the linting but rather in one of its dependencies, then I think the linting shouldn’t fail as it’s kind of a false alarm?

Such a failed linting should happen in the project that published the incorrect fields instead.

**Comment by nzakas** [comment] 2024-04-12 18:15
> Well, if node.js can resolve the module and the issue this plugin finds isn’t within the project that runs the linting but rather in one of its dependencies, then I think the linting shouldn’t fail as it’s kind of a false alarm?
> 
> Such a failed linting should happen in the project that published the incorrect fields instead.

I agree with this. The current setup for the retry package works fine in Node.js so I don't think it should be considered a problem. This seems more like something that other tooling is trying to enforce rather than an actual problem with the package.

That said, I can update the package to swap the order of exports.

**Comment by scagood** [comment] 2024-04-13 17:09
Agreed, I think I will do point two:
> Pr enhanced resolve to allow the error to be ignored via an option

It may also be worth seeing if we can add a rule to eslint-plugin-package-json too specifically about this if there is not one already 🤔

**Closed** 2024-06-05 09:25 UTC
Labels: bug, accepted, dependencies
